export const USER_AUTHENTICATE ='USER_AUTHENTICATE'
export const SIGN_IN_USER= 'SIGN_IN_USER'
export const ERROR_AUTHENTICATE_USER='ERROR_AUTHENTICATE_USER ' 
export const ERROR_SIGN_IN_USER = 'ERROR_SIGN_IN_USER ' 

export const UPLOAD_FILE_SUCCESFULY = 'UPLOAD_FILE_SUCCESFULY' 

export const SHOW_ALERT = 'SHOW_ALERT'
export const HIDDEN_ALERT = 'HIDDEN_ALERT'